### ISSUE TITLE
Condição vazia na linha 124

### ISSUE THREAD

**Issue by viniciussousaazevedo** [AlefAdonis/playgame#1]
Analisando o código, percebi que, caso a variável "esc_12" receba "2" como atribuição, nada será executado. O repositório ainda está em desenvolvimento? Como não tive certeza, achei interessante comentar isso...

> Percebi também que há um problema de endentação na linha 125, mas isso deve ser resolvido automaticamente a partir da resolução da linha 124

**Comment by alefadonis** [comment]
> Analisando o código, percebi que, caso a variável "esc_12" receba "2" como atribuição, nada será executado. O repositório ainda está em desenvolvimento? Como não tive certeza, achei interessante comentar isso...
> 
> > Percebi também que há um problema de endentação na linha 125, mas isso deve ser resolvido automaticamente a partir da resolução da linha 124

Fala Vinícius, tudo bem? 

Como eu ainda não atualizei o código, de fato essa atribuição nada faria, mas eu já consertei!
Obrigado por avisar!
